### ISSUE TITLE
Horses not being named correctly

### ISSUE THREAD

**Issue by abulujayn** [HavenRealms/Horses#2]
"And then when you claim the horse it doesn't set a name it sets a code"

Reported by Kuokoa via Discord.

**Comment by ArctoranDev** [comment]
This is a problem with the default horse names we have in our data file, I'll add it to the core plugin otherwise when using `/horse claim` you can actually specify the name after the claim argument to give it a custom name.

**Comment by ArctoranDev** [comment]
Problem has been fixed in commit 9c5ef0b1ae91c7c08e7c7aebc3460def29c5ef48
